### 1.5 난수 발생과 카운팅

In [1]:
import numpy as np

- 시드 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

In [5]:
np.random.choice(10, 5, replace=False)      # replace 쉽게 말해 True면 원소 중복가능

array([5, 6, 4, 0, 7])

In [6]:
np.random.choice(10, 5, replace=True)       # 복원 추출 

array([6, 4, 6, 8, 8])

In [54]:
x = np.random.randint(1, 46)
np.random.choice(x, 5)

array([2, 0, 2, 0, 2])

In [60]:
# 연습문제 3.5.1
# 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
# 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

x = np.random.randint(0, 2, size=100)
x.mean()

0.56

In [ ]:
# 연습 문제 3.5.2
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [78]:
x = np.random.normal(0, 0.01, 10)
price = 10000
for i in range(10):
    price = price * ( 1+x[i])
    price = int(round(price, 0))
    print(price, end=' ')

10165 10400 10398 10537 10590 10545 10533 10590 10532 10596 

In [83]:
# 100개의 수익률 생성
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [86]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price *= (1 + rate[i])
    price = int(round(price, 0))
    price_list.append(price)
price_list[-10:]

[10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691, 10497]

In [89]:
# 2. 어레이로 해결
price = 10000
price_array = np.empty(250, dtype=int)
for i in range(250):
    price *= (1 + rate[i])
    price = int(round(price, 0))
    price_array[i] = price

In [90]:
print(price_array[-10:])

[10814 10893 10674 10645 10588 10724 10739 10686 10691 10497]


- 데이터 카운팅

In [94]:
np.random.seed(2023)
dices = np.random.randint(1, 7, 100)

In [95]:
# 고유한 값
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [96]:
# 고유한 값과 돗수
np.unique(dices, return_counts = True)

(array([1, 2, 3, 4, 5, 6]), array([16, 18, 13, 15, 19, 19], dtype=int64))

In [97]:
indices, count = np.unique(dices, return_counts = True)
indices * count

array([ 16,  36,  39,  60,  95, 114], dtype=int64)

In [98]:
# 가중 평균
np.sum(indices * count) / np.sum(count)

3.6

In [99]:
a = np.array(['x', 'y', 'x', 'y', 'z', 'y'])
np.unique(a, return_counts=True)

(array(['x', 'y', 'z'], dtype='<U1'), array([2, 3, 1], dtype=int64))